import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

import domain.User;
import repozytorium.IRepozytorium;
import repozytorium.IRepozytoriumKatalog;

import unitofwork.IUnitOfWork;
import unitofwork.UnitOfWork;



public class Main {

	public static void main(String[] args) {

		String url="jdbc:hsqldb:hsql://localhost/workdb";
		User jnowak = new User();
		jnowak.setLogin("jarek");
		jnowak.setPassword("p@ssword");
		
		try {
			
			Connection connection = DriverManager.getConnection(url);
			IUnitOfWork uow = new UnitOfWork(connection);
			/*
			String createTableSql = 
					"CREATE TABLE users("
					+ "id int GENERATED BY DEFAULT AS IDENTITY,"
					+ "login VARCHAR(20),"
					+ "password VARCHAR(20)"
					+ ")";
			Statement createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			*/
			IRepozytoriumKatalog katalog = new RepozytoriumKatalog(connection, uow);
			
			
			katalog.getUsers().save(adamnowak);
			
			List<User> usersFromDb= katalog.getUsers().getAll();
			
			for(User userFromDb: usersFromDb)
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			User u = katalog.getUsers().get(2);
			u.setPassword("p@ssword");
			katalog.getUsers().update(u);
			katalog.getUsers().delete(usersFromDb.get(0));
		
			for(User userFromDb: katalog.getUsers().getAll())
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		System.out.println("koniec");
	}

}
